-- Generated by scripts/generate-seed.mjs from src/data/organisations.js. Do not edit by hand.
-- ⚠️ SAMPLE organisations for testing. Replace with real ones as agreements are signed.
insert into public.organisations (id, name, sector, code, seats) values
  ('lagos-foods', 'Lagos Foods Ltd', 'manufacturing', 'LAGOSFOODS', 250),
  ('bright-future', 'Bright Future Academy', 'education', 'BRIGHT2026', 80),
  ('harbour-insure', 'Harbour Health Insurance', 'insurance', 'HARBOUR', 1000)
on conflict (id) do update set name = excluded.name, sector = excluded.sector, code = excluded.code, seats = excluded.seats;
