/**
 * Builds the database's starting data from the app's own data files, so prices
 * and professionals in Supabase always match the app.
 *
 *   node scripts/generate-seed.mjs
 *
 * Writes:
 *   supabase/seed/products.sql              catalogue and prices (placeholders until you set real prices)
 *   supabase/seed/sample_professionals.sql  the 10 FICTIONAL sample professionals (for testing only)
 *
 * Run it again whenever you change src/data/products.js, src/data/professionals.js
 * or the delivery settings in src/config/shop.js, then paste the output into the
 * Supabase SQL Editor.
 */
import { writeFileSync } from 'node:fs'
import { PRODUCTS } from '../src/data/products.js'
import { PROFESSIONALS } from '../src/data/professionals.js'
import { shop } from '../src/config/shop.js'
import { ORGANISATIONS } from '../src/data/organisations.js'

const q = (v) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const arr = (xs) => `array[${xs.map(q).join(', ')}]::text[]`
const json = (o) => `${q(JSON.stringify(o))}::jsonb`

const products = `-- Generated by scripts/generate-seed.mjs from src/data/products.js. Do not edit by hand.
-- Prices are in naira and are the ONLY prices the server charges.
insert into public.products (id, name, unit, price, active) values
${PRODUCTS.map((p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.unit)}, ${p.price}, true)`).join(',\n')}
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price = excluded.price, active = excluded.active;

-- Delivery settings (from src/config/shop.js)
insert into public.shop_settings (id, delivery_fee, free_delivery_from, max_quantity, days_ahead, delivery_states)
values (1, ${shop.deliveryFee}, ${shop.freeDeliveryFrom}, ${shop.maxQuantity}, ${shop.daysAhead}, ${arr(shop.deliveryStates)})
on conflict (id) do update set delivery_fee = excluded.delivery_fee, free_delivery_from = excluded.free_delivery_from,
  max_quantity = excluded.max_quantity, days_ahead = excluded.days_ahead, delivery_states = excluded.delivery_states;
`

const professionals = `-- Generated by scripts/generate-seed.mjs from src/data/professionals.js. Do not edit by hand.
-- ⚠️ SAMPLE, FICTIONAL professionals for testing bookings. Before launch, delete them:
--      delete from public.professionals where id in (${PROFESSIONALS.map((p) => q(p.id)).join(', ')});
--    and add real professionals only after verifying their registration.
insert into public.professionals (id, name, title, specialty, years, languages, focus, types, fees, schedule, bio, verified_at, active) values
${PROFESSIONALS.map((p) => `  (${q(p.id)}, ${q(p.name)}, ${q(p.title)}, ${q(p.specialty)}, ${p.years ?? 0}, ${arr(p.languages)}, ${arr(p.focus ?? [])}, ${arr(p.types)}, ${json(p.fees)}, ${json(p.schedule)}, ${q(p.bio)}, now(), true)`).join(',\n')}
on conflict (id) do update set name = excluded.name, title = excluded.title, fees = excluded.fees, schedule = excluded.schedule, types = excluded.types;
`

const organisations = `-- Generated by scripts/generate-seed.mjs from src/data/organisations.js. Do not edit by hand.
-- ⚠️ SAMPLE organisations for testing. Replace with real ones as agreements are signed.
insert into public.organisations (id, name, sector, code, seats) values
${ORGANISATIONS.map((o) => `  (${q(o.id)}, ${q(o.name)}, ${q(o.sector)}, ${q(o.code)}, ${o.seats})`).join(',\n')}
on conflict (id) do update set name = excluded.name, sector = excluded.sector, code = excluded.code, seats = excluded.seats;
`

writeFileSync(new URL('../supabase/seed/sample_organisations.sql', import.meta.url), organisations)
writeFileSync(new URL('../supabase/seed/products.sql', import.meta.url), products)
writeFileSync(new URL('../supabase/seed/sample_professionals.sql', import.meta.url), professionals)
console.log(`Wrote ${PRODUCTS.length} products, ${PROFESSIONALS.length} sample professionals and ${ORGANISATIONS.length} sample organisations.`)
